services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=/prometheus'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - cv-challenge-network
    depends_on: 
      - cadvisor

  grafana: 
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://grafana:3000/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - cv-challenge-network
    depends_on:
      - prometheus
      - loki

  loki: 
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - cv-challenge-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped 
    volumes:
      - /var/log:/var/log:ro
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - cv-challenge-network
    depends_on:
      - loki
      - backend
      - frontend
      - db
      - adminer

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8085:8000"
    networks:
      - cv-challenge-network
    depends_on:
      - backend
      - frontend
      - db

volumes:
  prometheus_data:
  grafana_data:
  loki_data: