global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']  # Assuming your backend exposes metrics

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:5173']  # If your frontend exposes metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
